name: Jekyll Deploy

on:
  push:
    branches:
      - master
      # note: (vim) updated with
      #  :execute 'r!cd ' . expand('%:h') . ' && git cb || echo "error: $?" 1>&2'
  #schedule:
  #  # redeploy every morning to update unpublished pages
  #  - cron: "0 2 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository (no submodules)
        uses: actions/checkout@v2
        with:
          submodules: false

      - name: Checkout public modules
        run: git submodule update --init --depth 1 --recursive modules/pub/

      # TODO: make 'local/bin/reposetup' a symlink to a file in a public module (should I put this in the "blog common" one for now?)
      # TODO: other values:
      #   --mode={ prod | dev (default) }
      #   --site={ github | (anything else) }
      # LATER: - name: Post-checkout setup
      # LATER:   run: local/bin/reposetup --mode=prod --site=github post-checkout

      #- name: Cache gems
      #  uses: actions/cache@v1
      #  with:
      #    path: vendor/gems
      #    key: ${{ runner.os }}-build-${{ hashFiles('**/Gemfile.lock') }}
      #    restore-keys: |
      #      ${{ runner.os }}-build-
      #      ${{ runner.os }}-

      # 2020.12.04: updated using example from: https://github.com/actions/cache/blob/main/examples.md#ruby---bundler
      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/gems
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build & Deploy to GitHub Pages
        # orig: uses: DavidS/jekyll-deploy@main
        # 2020.12.04: disabled (choked on non-existing 'gh-pages' branch):
        #- uses: DavidS/jekyll-deploy@1.1.1
        uses: DavidS/jekyll-deploy@main
        env:
          JEKYLL_ENV: production
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        #with:
        #  # Set to "true" to only build, but not deploy. This is useful for PR testing
        #  #build-only: # optional, default is false
